### PR TITLE
fix reinit function

### PR DESCRIPTION
**Pull request by AjayThorve**
Quick fix PR to fix the `_reinit_all_charts` function, which was no longer working due to the recent refactors

### CODE REVIEW

**Comment by bryevdv** [comment]
@AjayThorve is there a good test case or example to run to see before/after? Changes look OK at a glance but I don't really have any context for what exactly was broken

**Comment by AjayThorve** [comment]
@bryevdv (pushed one more change after you reviewed). basically don't need to reinitialize `data_size_indicator`, separately, as that was fixed in a previous PR. 

Current implementation was reinitializing it twice (line 320, 325), and this was leading to some inconsistencies in data size values if we ran `d.app()` twice, or `d.show()` twice in a row. 

Ideally, it should just reinitialize all chart if we rerun the function, which now happens properly

**Review by bryevdv — APPROVED** [review]

**Comment by AjayThorve** [comment]
@gpucibot merge

**Comment by AjayThorve** [comment]
rerun tests

**Pull request merged**
