### PR TITLE
revert pyppeteer dependency changes

### PR DESCRIPTION
**Pull request by AjayThorve**
reverts the removal of pyppeteer since CI issues seem to be resolved.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by AjayThorve** [comment]
rerun tests

**Review by bryevdv — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by AjayThorve** [comment]
Need to update integration repo first with the updated pyppeteer version for the CI to pass

**Comment by AjayThorve** [comment]
rerun test

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by AjayThorve** [comment]
@gpucibot merge

**Pull request merged**
