### PR TITLE
Dropping Python 3.8

### PR DESCRIPTION
**Pull request by divyegala**
This PR drops Python 3.8 in favor of 3.9.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]
suprisingly this PR passed CI despite the its upstream RAPIDS dependencies not having published packages for `23.06` `3.9`. It looks like it's picking up old stable `3.9` packages from `22.12`.

Seems like we should probably adjust our nightly workflows to remove the stable Anaconda.org channels for nightly/PR workflows.

that'll be a discussion for another day.

**Comment by divyegala** [comment]
@ajschmidt8 can we merge this in that case?

**Comment by vyasr** [comment]
@exactlyallan @AjayThorve could we get a Python review here, and a merge when ready? Thank you!

**Review by AjayThorve — APPROVED** [review]
LGTM!

**Pull request merged**
