### PR TITLE
Fix/follow up to #303

### PR DESCRIPTION
**Pull request by AjayThorve**
Follow up PR to #303, fixes theme related bugs, which were introduced in the previous PR, while updating panel and bokeh version support. 

This PR also fixes(handles), a weird issue where the bokeh x-axis data in CDS is converted from datetime to float during runtime, which caused a bunch of issues in the computing queries.

Will have to investigate further and try and fix this issue in the base libraries instead of cuxfilter though, more work to follow regarding that.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
rerun tests

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
> This PR also fixes(handles), a weird issue where the bokeh x-axis data in CDS is converted from datetime to float during runtime, which caused a bunch of issues in the computing queries

Definitely would like to understand whatever is going on with this. I have not seen any other reports about types mutating and I can't find any 2.3+ PRs that seem relevant either

**Comment by AjayThorve** [comment]
> > This PR also fixes(handles), a weird issue where the bokeh x-axis data in CDS is converted from datetime to float during runtime, which caused a bunch of issues in the computing queries
> 
> Definitely would like to understand whatever is going on with this. I have not seen any other reports about types mutating and I can't find any 2.3+ PRs that seem relevant either

So its more of a panel issue, whenever we start a dashboard with panel, the bokeh charts with datetime axis gets converted to float. 

bokeh.io.show works fine, and does not have that issue

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
@gpucibot merge

**Pull request merged**
