### PR TITLE
Prevent path conflict in builds

### PR DESCRIPTION
**Pull request by AyodeAwe**
Contributes to https://github.com/rapidsai/build-planning/issues/54

Ensures that conda builds will fail in the presence of multiple packages with identical paths

### CODE REVIEW

**Review by AjayThorve — APPROVED** [review]

**Comment by jameslamb** [comment]
Converting this back to draft until the issues are fixed.

**Comment by jameslamb** [comment]
Looking at the logs today, I realized this is not failing for any *build-time* reasons. It's just test failures 🤔 

Like this:

```text
FAILED cuxfilter/tests/charts/deckgl/test_deckgl.py::TestDeckGL::test_init[cux_df1] - TypeError: __init__() got an unexpected keyword argument 'as_index'
```

([build link](https://github.com/rapidsai/cuxfilter/actions/runs/8740113054/job/23983676548?pr=583))

I strongly suspect that isn't related to the changes on this PR, and that that'll block any PR into `cuxfilter` until it's resolved.

**Comment by rjzamora** [comment]
It looks like cuxfilter has a few test failures related to the dask-expr migration in `dask.dataframe`.  Most of the migration issues are being tracked in https://github.com/rapidsai/cudf/issues/15027

I'll add a note about `cuxfilter` to that meta issue, and will investigate as soon as I can. 

In the mean time, it should be fine to set the following environment variable in CI (before `dask.dataframe` is ever imported):

```
export DASK_DATAFRAME__QUERY_PLANNING=False
```

(This is what cugraph is currently doing).

**Comment by AjayThorve** [comment]
@AyodeAwe adding the following env variable to both ./ci/test_python.sh and ci/test_wheel.sh should resolve the tests for now:

ci/test_python.sh
```bash
DASK_DATAFRAME__QUERY_PLANNING=False pytest \
```
ci/test_wheel.sh
```bash
DASK_DATAFRAME__QUERY_PLANNING=False python -m pytest -n 8 ./python/cuxfilter/tests
```

**Comment by jameslamb** [comment]
Thanks for the fixes in #593! Just merged them in here. If that fixes CI here I'll put this up for review.

**Comment by jameslamb** [comment]
Alright this looks good! @AjayThorve I think this could be merged. Let me know if you have any other questions or concerns about what it's trying to accomplish.

**Review by AjayThorve — APPROVED** [review]
Lgtm!

**Review by raydouglass — APPROVED** [review]

**Pull request merged**
