### PR TITLE
update docstrings examples to fix #328

### LINKED ISSUE #328: [WIP] cuxFilter Documentation Example Errors
**Describe the bug**
cuxFilter documentation has errors in some of the examples present. There are examples that relies on code that cannot be ran without errors in the most recent RAPIDS releases. I've began testing going back to 0.19 and there may have been some change to the API before that release. Not sure if these changes were intentional or if it was an uncaught bug.

**Steps/Code to reproduce bug**
1.Go to Rapids cuxFilter documentation [website](https://docs.rapids.ai/api/cuxfilter/stable/index.html)
2.Click on the cuxFilter API Reference [link](https://docs.rapids.ai/api/cuxfilter/stable/dataframe.html)
3.Run the content for the examples therein as illustrated below

**Expected behavior**
There will be several examples that will create an error. Many examples miss details that could aide in implementation. The code will be a few commits behind from the 21.10 repo.

**Environment details (please complete the following information):**
 - Environment location: Paperspace
 - Linux Distro/Architecture: Ubuntu 18.04 amd64
 - GPU Model/Driver: P5000
 - CUDA: 11.4
 - Method of cuDF & cuxFilter install: 
```
docker pull rapidsai/rapidsai:21.10-cuda11.4-runtime-ubuntu18.04-py3.8
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai:21.10-cuda11.4-runtime-ubuntu18.04-py3.8
```
**Additional context**
Examples of Discrepancies:
Example # 1

```
import cuxfilter
cux_df = cuxfilter.DataFrame.from_arrow(
    './location/of/dataframe.arrow'
    )
```

Error thrown below:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-4b9c838bd984> in <module>
      1 import cuxfilter
----> 2 cux_df = cuxfilter.DataFrame.from_arrow(
      3     './location/of/dataframe.arrow'
      4     )

/opt/conda/envs/rapids/lib/python3.8/site-packages/cuxfilter/dataframe.py in from_arrow(cls, dataframe_location)
     51         """
     52         if isinstance(dataframe_location, str):
---> 53             df = cudf.DataFrame.from_arrow(read_arrow(dataframe_location))
     54         else:
     55             df = cudf.DataFrame.from_arrow(dataframe_location)

/opt/conda/envs/rapids/lib/python3.8/site-packages/cuxfilter/dataframe.py in read_arrow(source)
     11 def read_arrow(source):
     12     # print('reading arrow file as arrow table from disk')
---> 13     reader = pa.RecordBatchStreamReader(source)
     14     pa_df = reader.read_all()
     15     return pa_df

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/ipc.py in __init__(self, source)
     43 
     44     def __init__(self, source):
---> 45         self._open(source)
     46 
     47 

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/ipc.pxi in pyarrow.lib._RecordBatchStreamReader._open()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/ipc.pxi in pyarrow.lib._get_input_stream()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/io.pxi in pyarrow.lib.get_input_stream()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/io.pxi in pyarrow.lib.get_native_file()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/io.pxi in pyarrow.lib.memory_map()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/io.pxi in pyarrow.lib.MemoryMappedFile._open()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.pyarrow_internal_check_status()

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

FileNotFoundError: [Errno 2] Failed to open local file './location/of/dataframe.arrow'. Detail: [errno 2] No such file or directory
```

Where I am not able to test without dataframe.arrow to determine success 

Example # 2

```
import cuxfilter
import cudf, cugraph
edges = cudf.DataFrame(
    {
        'source': [0, 1, 2, 3, 4],
        'target':[0,1,2,3,4],
        'weight':[4,4,2,6,7],
    }
)
G = cugraph.Graph()
G.from_cudf_edgelist(edges)
cux_df = cuxfilter.DataFrame.load_graph((G.nodes(), G.edges()))
```
Where from_cudf_edgelist currently expects parameters in a different fashion. 
 
Error thrown below:
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-5-792c12b6d9cd> in <module>
      9 )
     10 G = cugraph.Graph()
---> 11 G.from_cudf_edgelist(edges)
     12 cux_df = cuxfilter.DataFrame.load_graph((G.nodes(), G.edges()))

/opt/conda/envs/rapids/lib/python3.8/site-packages/cugraph/structure/graph_classes.py in from_cudf_edgelist(self, input_df, source, destination, edge_attr, renumber)
    145               self._Impl.adjlist is not None):
    146             raise Exception("Graph already has values")
--> 147         self._Impl._simpleGraphImpl__from_edgelist(input_df,
    148                                                    source=source,
    149                                                    destination=destination,

/opt/conda/envs/rapids/lib/python3.8/site-packages/cugraph/structure/graph_implementation/simpleGraph.py in __from_edgelist(self, input_df, source, destination, edge_attr, renumber)
    103         ):
    104             # FIXME: Raise concrete Exceptions
--> 105             raise Exception(
    106                 "source column names and/or destination column "
    107                 "names not found in input. Recheck the source and "

Exception: source column names and/or destination column names not found in input. Recheck the source and destination parameters
```

Example # 3

```
import cudf
import cuxfilter
from cuxfilter.charts import bokeh
df = cudf.DataFrame(
    {
        'key': [0, 1, 2, 3, 4],
        'val':[float(i + 10) for i in range(5)]
    }
)
cux_df = cuxfilter.DataFrame.from_dataframe(df)
line_chart_1 = bokeh.line(
    'key', 'val', data_points=5, add_interaction=False
)
line_chart_2 = bokeh.bar(
    'val', 'key', data_points=5, add_interaction=False
)
d = cux_df.dashboard([line_chart_1, line_chart_2])
await d.preview()
```
Where the browser will not produce any output without failing first. 

Error thrown below:
```
---------------------------------------------------------------------------
BrowserError                              Traceback (most recent call last)
<ipython-input-11-b904865afa76> in <module>
     16 )
     17 d = cux_df.dashboard([line_chart_1, line_chart_2])
---> 18 await d.preview()

/opt/conda/envs/rapids/lib/python3.8/site-packages/cuxfilter/dashboard.py in preview(self)
    537             port=port, websocket_origin=url, show=False, start=True
    538         )
--> 539         await screengrab("http://" + url)
    540         self.stop()
    541 

/opt/conda/envs/rapids/lib/python3.8/site-packages/cuxfilter/assets/screengrab.py in screengrab(url)
      3 
      4 async def screengrab(url):
----> 5     browser = await launch({"slowMo": 5}, args=["--no-sandbox"])
      6     page = await browser.newPage()
      7     await page.setViewport(

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyppeteer/launcher.py in launch(options, **kwargs)
    305         option with extreme caution.
    306     """
--> 307     return await Launcher(options, **kwargs).launch()
    308 
    309 

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyppeteer/launcher.py in launch(self)
    166 
    167         connectionDelay = self.slowMo
--> 168         self.browserWSEndpoint = get_ws_endpoint(self.url)
    169         logger.info(f'Browser listening on: {self.browserWSEndpoint}')
    170         self.connection = Connection(self.browserWSEndpoint, self._loop, connectionDelay, )

/opt/conda/envs/rapids/lib/python3.8/site-packages/pyppeteer/launcher.py in get_ws_endpoint(url)
    225     while (True):
    226         if time.time() > timeout:
--> 227             raise BrowserError('Browser closed unexpectedly:\n')
    228         try:
    229             with urlopen(url) as f:

BrowserError: Browser closed unexpectedly:
```

**Desired outcome**
Examples present in cuxFilter documentation should be ready to replicated and implemented with less effort.  Examples should reflect the commits made to the repositories during each release cycle. cuxFilter functions and models work as expected.

**Request impacts**
Our cuxFilter documentation is public and requires accurate information - Medium Priority

@AjayThorve  @taureandyernv for awareness

### PR DESCRIPTION
**Pull request by AjayThorve**

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
@gpucibot merge

**Pull request merged**
