### PR TITLE
Re-enable `graphs.ipynb` notebook in CI

### PR DESCRIPTION
**Pull request by ajschmidt8**
The `graphs.ipynb` notebook was disabled in #426 due to some upstream issues with `cugraph`.

This PR reverts that change to re-enable the notebook.

### CODE REVIEW

**Comment by AjayThorve** [comment]
> cc: @AjayThorve.
> 
> We can merge this when the upstream issues are fixed.

@ajschmidt8, CI is passing,  this looks good to merge ?

**Comment by ajschmidt8** [comment]
> > cc: @AjayThorve.
> > We can merge this when the upstream issues are fixed.
> 
> @ajschmidt8, CI is passing, this looks good to merge ?

I just spoke with Rick and he said the issue here is intermittent. So we might've gotten lucky on this last run.

I'm going to merge the latest changes to this PR (which will trigger a new CI run) and we can see how it goes.

**Review by AjayThorve — APPROVED** [review]

**Comment by AjayThorve** [comment]
@ajschmidt8 I think one of the ops-codeowners will have to approve this

**Review by AyodeAwe — APPROVED** [review]

**Pull request merged**
