### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by AjayThorve**
Follow up to #494, updates API docs and screenshots.

cc @exactlyallan

### CODE REVIEW

**Review by exactlyallan — APPROVED** [review]
@AjayThorve Looks good - thanks for all the screenshot updates. One quick thing, just remove the architecture diagram from "10min to cuxfilter" until we can update it - still mentions datatiles.

**Comment by raydouglass** [comment]
Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

**Comment by AjayThorve** [comment]
> Removing `ops-codeowners` from the required reviews since it doesn't seem there are any file changes that we're responsible for. Feel free to add us back if necessary.

Thanks @raydouglass

**Comment by AjayThorve** [comment]
@raydouglass can we merge this in 23.08, it now says the base branch is not under active development.

**Comment by raydouglass** [comment]
> can we merge this in 23.08, it now says the base branch is not under active development.

Yes. I thought it was merged so I trigger to switch over to `23.10`. I'll admin merge this PR.

**Pull request merged**
