### PR TITLE
Close open ended dependencies

### PR DESCRIPTION
**Pull request by AjayThorve**
- minor fixes and closing open-ended dependencies for bokeh, panel, pyproj & geopandas

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Review by bryevdv — APPROVED** [review]

**Review by mike-wendt — APPROVED** [review]
@AjayThorve can you also update these to match?
- https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/versions.yaml#L32-L33
- https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/versions.yaml#L108-L109

**Comment by AjayThorve** [comment]
> @AjayThorve can you also update these to match?
> 
> * https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/versions.yaml#L32-L33
> * https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/versions.yaml#L108-L109

@mike-wendt I'm on it, will create a PR shortly

**Comment by mike-wendt** [comment]
> > @AjayThorve can you also update these to match?
> > 
> > * https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/versions.yaml#L32-L33
> > * https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/versions.yaml#L108-L109
> 
> @mike-wendt I'm on it, will create a PR shortly

@AjayThorve thanks just add in the others that I missed from your environment files if they are necessary to pin as well

**Pull request merged**
