### PR TITLE
Fix libwebp dependency

### PR DESCRIPTION
**Pull request by AjayThorve**
Replace libwebp with libwebp-base to resolve dependency conflict with the [cucim](https://github.com/rapidsai/cucim) package.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Ajay! 🙏

Can you please also change this line?

https://github.com/rapidsai/cuxfilter/blob/bf585e206c84799ed03c2e1c465ea91bf3b1e649/conda/recipes/cuxfilter/meta.yaml#L36

**Comment by AjayThorve** [comment]
> Thanks Ajay! 🙏
> 
> Can you please also change this line?
> 
> https://github.com/rapidsai/cuxfilter/blob/bf585e206c84799ed03c2e1c465ea91bf3b1e649/conda/recipes/cuxfilter/meta.yaml#L36

done!

**Review by raydouglass — APPROVED** [review]

**Review by exactlyallan — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
