### PR TITLE
Fix/examples

### PR DESCRIPTION
**Pull request by AjayThorve**
Minor PR to fix usage of `legend_postion` parameter in example notebooks, which had an incorrect value(as per the recent api changes) leading to errors.

### CODE REVIEW

**Comment by AjayThorve** [comment]
rerun tests

**Comment by bryevdv** [comment]
LGTM not sure why tests are failing

**Comment by AjayThorve** [comment]
> LGTM not sure why tests are failing

Thanks bryan, I think the failure is not related to this PR, it's a dask-cudf import issue which should be fixed now, trying to rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
rerun tests

**Comment by AjayThorve** [comment]
@gpucibot merge

**Review by exactlyallan — APPROVED** [review]
Was this an API change issue?

**Comment by AjayThorve** [comment]
> Was this an API change issue?

Yes, just one parameter having a value no longer valid in a couple of places.

**Comment by bryevdv** [comment]
I guess this was changed in 2.3 to require being explicit about both dimensions for consistency i.e. `center_center`. There probably should have been an `accepts` clause added for back-compat, not sure why it wasn't

https://github.com/bokeh/bokeh/pull/10779/files

**Pull request merged**
