### PR TITLE
Allow CuPy 11

### PR DESCRIPTION
**Pull request by jakirkham**
Allows cuxfilter to be installed with CuPy 11.

xref: https://github.com/rapidsai/integration/pull/508

### CODE REVIEW

**Comment by jakirkham** [comment]
Could someone please help add the appropriate labels here?

**Review by sevagh — APPROVED** [review]

**Comment by jakirkham** [comment]
Thank you both! 🙏

**Comment by AjayThorve** [comment]
rerun tests

**Comment by jakirkham** [comment]
Filed issue ( https://github.com/rapidsai/cuxfilter/issues/384 ) to summarize what we are seeing on CI.

**Review by AjayThorve — APPROVED** [review]
looks good, cupy 11 doesn't cause any issues with cuxfilter. Thanks!

**Comment by AjayThorve** [comment]
@gpucibot merge

**Pull request merged**
