### PR TITLE
Allow CuPy 9 to be used with cuxfilter

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
rerun tests

CI had an [HTTP timeout error in one job]( https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/rapidsai%2Fgpuci-v0.20%2Fcuxfilter%2Fprb%2Fcuxfilter-cpu-build/detail/cuxfilter-cpu-build/13/pipeline )

**Review by ajschmidt8 — APPROVED** [review]

**Review by AjayThorve — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by ajschmidt8** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
