### PR TITLE
update panel version

### LINKED ISSUE #360: [BUG] ImportError in Panel when importing cuxfilter
**Describe the bug**
Nightly package contains a recent [bug in Panel](https://github.com/holoviz/panel/issues/3260), which has been fixed in the latest version 0.12.7.

**Steps/Code to reproduce bug**

`import cuxfilter`

Triggers an ImportError..
```
ImportError: cannot import name 'Markup' from 'jinja2' (/home/mmccarty/miniconda3/envs/rapids-22.04/lib/python3.8/site-packages/jinja2/__init__.py)
```

**Expected behavior**
The import should succeed.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)] - All
 - Method of cuxfilter install: [conda, Docker, or from source] - conda & Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - `docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 -v /home/mmccarty/sandbox/rapids/cloud-ml-examples:/rapids/notebooks/cloud-ml-examples rapidsai/rapidsai-core-dev-nightly:22.04-cuda11.5-devel-ubuntu20.04-py3.8`

### PR DESCRIPTION
**Pull request by AjayThorve**
fixes #360

### CODE REVIEW

**Comment by AjayThorve** [comment]
waiting for panel `0.12.7` to be uploaded to conda-forge for CI to pass

**Comment by jakirkham** [comment]
Thanks Ajay! 😀

Should we update the `integration` repo's [`panel` version constraint]( https://github.com/rapidsai/integration/blob/b01cb3b4552f945d3dd2433cecaf6c52ab4307e8/conda/recipes/versions.yaml#L125L126 ) as well?

**Comment by mmccarty** [comment]
You could also pin `jinja2=2.11.3`, if there are no other issues with that version.

**Comment by jakirkham** [comment]
Yeah we were planning to update to the new `panel` package once release. Already have PR ( https://github.com/conda-forge/panel-feedstock/pull/48 ) up to fix that. Just need a review from the `panel` developers.

**Comment by AjayThorve** [comment]
> You could also pin `jinja2=2.11.3`, if there are no other issues with that version.

I think there might be, the @rapidsai/docker repo has pinned the jinja2 package at a higher version (https://github.com/rapidsai/docker/blob/branch-22.04/requirements.txt) for CI

**Comment by ajschmidt8** [comment]
> > You could also pin `jinja2=2.11.3`, if there are no other issues with that version.
> 
> I think there might be, the @rapidsai/docker repo has pinned the jinja2 package at a higher version (https://github.com/rapidsai/docker/blob/branch-22.04/requirements.txt) for CI

That's safe to ignore. I can adjust that pin if necessary.

**Comment by AjayThorve** [comment]
> > > You could also pin `jinja2=2.11.3`, if there are no other issues with that version.
> > 
> > 
> > I think there might be, the @rapidsai/docker repo has pinned the jinja2 package at a higher version (https://github.com/rapidsai/docker/blob/branch-22.04/requirements.txt) for CI
> 
> That's safe to ignore. I can adjust that pin if necessary. It doesn't have any effect on any of the other RAPIDS packages.

Well in that case, pinning jinja2 might resolve panel issues without waiting for a `0.12.7` release, if that works, I'll go ahead and push the pin for that as well!

**Comment by AjayThorve** [comment]
> Thanks Ajay! grinning
> 
> Should we update the `integration` repo's [`panel` version constraint](https://github.com/rapidsai/integration/blob/b01cb3b4552f945d3dd2433cecaf6c52ab4307e8/conda/recipes/versions.yaml#L125L126) as well?

@jakirkham added the PR to integration repo -> https://github.com/rapidsai/integration/pull/454

**Comment by ajschmidt8** [comment]
> `panel` has been updated grinning

I think we can unpin the Jinja pkg now then, right?

**Comment by AjayThorve** [comment]
> > `panel` has been updated grinning
> 
> I think we can unpin the Jinja pkg now then, right?

yep, just tested locally, newer panel works with all jinja versions, unpinned it.

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
admin merging since all tests have passed except arm due to some machine issues.

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
